export {
  remoteConfiguredHostAgentSchema,
  remoteConfiguredHostItemSchema,
  remoteDiscoveredAgentItemSchema,
  remoteDiscoveredHostDetailsSchema,
  remoteHostDetailsSchema,
  remotePlatformDirectorySchema,
  remotePlatformOverviewSchema,
  remoteSessionsGatewayResponseSchema,
  remoteSessionSummarySchema,
  remoteTenantScopeSchema,
} from "@dosc-syspro/contracts/remote";

export type {
  RemoteAccessPolicy,
  RemoteAccessScope,
  RemoteAgentCommandStatus,
  RemoteAgentCommandType,
  RemoteAgentInstallStage,
  RemoteAgentLifecycleStatus,
  RemoteCompanyContextItem,
  RemoteConfiguredHostAgent,
  RemoteConfiguredHostItem,
  RemoteDiscoveredAgentItem,
  RemoteDiscoveredHostDetails,
  RemoteDiscoveredHostStatus,
  RemoteHostDetails,
  RemoteHostStatus,
  RemoteHostSummary,
  RemoteHostSysproUpdateItem,
  RemoteModuleSettings,
  RemoteModuleSettingsActionResponse,
  RemoteOperationalStatus,
  RemoteProductStatus,
  RemotePlatformDirectory,
  RemotePlatformEndpoint,
  RemotePlatformModule,
  RemotePlatformOverview,
  RemotePaginationMeta,
  RemotePlatformRoadmapPhase,
  RemotePlatformStatus,
  RemoteSessionAuditAction,
  RemoteSessionAuditEvent,
  RemoteSessionAuditModel,
  RemoteSessionAuditSource,
  RemoteSessionStatus,
  RemoteSessionSummary,
  RemoteTenantScope,
} from "@dosc-syspro/contracts/remote";
