import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  test: {
    environment: "node",
    globals: true,
    include: ["tests/**/*.test.ts"],
    clearMocks: true,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
      "server-only": path.resolve(__dirname, "tests/mocks/server-only.ts"),
      "@dosc-syspro/shared/logger": path.resolve(__dirname, "../../packages/shared/src/logger.ts"),
      "@dosc-syspro/shared/request-auth": path.resolve(__dirname, "../../packages/shared/src/request-auth.ts"),
      "@dosc-syspro/shared/action-rate-limit": path.resolve(__dirname, "../../packages/shared/src/action-rate-limit.ts"),
      "@dosc-syspro/shared/action-error-handler": path.resolve(__dirname, "../../packages/shared/src/action-error-handler.ts"),
      "@dosc-syspro/shared": path.resolve(__dirname, "../../packages/shared/src/index.ts"),
      "@dosc-syspro/core/config/route-access": path.resolve(__dirname, "../../packages/core/src/config/route-access.ts"),
      "@dosc-syspro/core/config/role-labels": path.resolve(__dirname, "../../packages/core/src/config/role-labels.ts"),
      "@dosc-syspro/core/config/contract-blocking": path.resolve(__dirname, "../../packages/core/src/config/contract-blocking.ts"),
      "@dosc-syspro/core/config/ticket-state-matrix": path.resolve(__dirname, "../../packages/core/src/config/ticket-state-matrix.ts"),
      "@dosc-syspro/core/config/tickets-workflow": path.resolve(__dirname, "../../packages/core/src/config/tickets-workflow.ts"),
      "@dosc-syspro/core/entities/release": path.resolve(__dirname, "../../packages/core/src/entities/release.entity.ts"),
      "@dosc-syspro/core/services/ticket-sla": path.resolve(__dirname, "../../packages/core/src/services/ticket-sla.service.ts"),
      "@dosc-syspro/core": path.resolve(__dirname, "../../packages/core/src/index.ts"),
      "@dosc-syspro/contracts/agent": path.resolve(__dirname, "../../packages/contracts/src/agent/index.ts"),
      "@dosc-syspro/contracts/automation": path.resolve(__dirname, "../../packages/contracts/src/automation/index.ts"),
      "@dosc-syspro/contracts/chatwoot": path.resolve(__dirname, "../../packages/contracts/src/chatwoot/index.ts"),
      "@dosc-syspro/contracts/company": path.resolve(__dirname, "../../packages/contracts/src/company/index.ts"),
      "@dosc-syspro/contracts/contact": path.resolve(__dirname, "../../packages/contracts/src/contact/index.ts"),
      "@dosc-syspro/contracts/contract": path.resolve(__dirname, "../../packages/contracts/src/contract/index.ts"),
      "@dosc-syspro/contracts/crm": path.resolve(__dirname, "../../packages/contracts/src/crm/index.ts"),
      "@dosc-syspro/contracts/dashboard": path.resolve(__dirname, "../../packages/contracts/src/dashboard/index.ts"),
      "@dosc-syspro/contracts/evolution": path.resolve(__dirname, "../../packages/contracts/src/evolution/index.ts"),
      "@dosc-syspro/contracts/evolution-settings": path.resolve(__dirname, "../../packages/contracts/src/evolution/evolution-settings.types.ts"),
      "@dosc-syspro/contracts/evolution-webhook": path.resolve(__dirname, "../../packages/contracts/src/evolution/evolution-webhook.types.ts"),
      "@dosc-syspro/contracts/remote": path.resolve(__dirname, "../../packages/contracts/src/remote/index.ts"),
      "@dosc-syspro/contracts/remote-module-settings": path.resolve(__dirname, "../../packages/contracts/src/remote/remote-module-settings.types.ts"),
      "@dosc-syspro/contracts/platform-notifications": path.resolve(__dirname, "../../packages/contracts/src/shared/platform-notifications.types.ts"),
      "@dosc-syspro/contracts/settings": path.resolve(__dirname, "../../packages/contracts/src/settings/index.ts"),
      "@dosc-syspro/contracts/sefaz-routes": path.resolve(__dirname, "../../packages/contracts/src/sefaz/sefaz-routes.types.ts"),
      "@dosc-syspro/contracts/sefaz-endpoints": path.resolve(__dirname, "../../packages/contracts/src/sefaz/sefaz-endpoints.types.ts"),
      "@dosc-syspro/contracts/ticket": path.resolve(__dirname, "../../packages/contracts/src/ticket/index.ts"),
      "@dosc-syspro/contracts/address": path.resolve(__dirname, "../../packages/contracts/src/shared/address.types.ts"),
      "@dosc-syspro/contracts/documento": path.resolve(__dirname, "../../packages/contracts/src/documento/documento.types.ts"),
      "@dosc-syspro/contracts/documento-config": path.resolve(__dirname, "../../packages/contracts/src/documento/documento-config.types.ts"),
      "@dosc-syspro/contracts/user": path.resolve(__dirname, "../../packages/contracts/src/user/index.ts"),
      "@dosc-syspro/contracts": path.resolve(__dirname, "../../packages/contracts/src/index.ts"),
      "@dosc-syspro/database": path.resolve(__dirname, "../../packages/database/src/index.ts"),
    },
  },
});
