import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  test: {
    environment: "node",
    globals: true,
    include: ["tests/**/*.test.ts"],
    clearMocks: true,
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
      "@dosc-syspro/shared": path.resolve(__dirname, "../../packages/shared/src/index.ts"),
      "@dosc-syspro/shared/logger": path.resolve(__dirname, "../../packages/shared/src/logger.ts"),
      "@dosc-syspro/shared/request-auth": path.resolve(__dirname, "../../packages/shared/src/request-auth.ts"),
      "@dosc-syspro/shared/action-rate-limit": path.resolve(__dirname, "../../packages/shared/src/action-rate-limit.ts"),
      "@dosc-syspro/shared/action-error-handler": path.resolve(__dirname, "../../packages/shared/src/action-error-handler.ts"),
      "@dosc-syspro/core": path.resolve(__dirname, "../../packages/core/src/index.ts"),
      "@dosc-syspro/core/config/route-access": path.resolve(__dirname, "../../packages/core/src/config/route-access.ts"),
      "@dosc-syspro/core/config/role-labels": path.resolve(__dirname, "../../packages/core/src/config/role-labels.ts"),
      "@dosc-syspro/core/config/contract-blocking": path.resolve(__dirname, "../../packages/core/src/config/contract-blocking.ts"),
      "@dosc-syspro/core/config/ticket-state-matrix": path.resolve(__dirname, "../../packages/core/src/config/ticket-state-matrix.ts"),
      "@dosc-syspro/core/config/tickets-workflow": path.resolve(__dirname, "../../packages/core/src/config/tickets-workflow.ts"),
      "@dosc-syspro/core/entities/ticket": path.resolve(__dirname, "../../packages/core/src/entities/ticket.ts"),
      "@dosc-syspro/core/entities/release": path.resolve(__dirname, "../../packages/core/src/entities/release.ts"),
      "@dosc-syspro/core/services/ticket-sla": path.resolve(__dirname, "../../packages/core/src/services/ticket-sla.ts"),
      "@dosc-syspro/contracts": path.resolve(__dirname, "../../packages/contracts/src/index.ts"),
      "@dosc-syspro/contracts/settings": path.resolve(__dirname, "../../packages/contracts/src/settings.ts"),
      "@dosc-syspro/contracts/sefaz-routes": path.resolve(__dirname, "../../packages/contracts/src/sefaz-routes.ts"),
      "@dosc-syspro/contracts/sefaz-endpoints": path.resolve(__dirname, "../../packages/contracts/src/sefaz-endpoints.ts"),
      "@dosc-syspro/contracts/ticket-form": path.resolve(__dirname, "../../packages/contracts/src/ticket-form.ts"),
      "@dosc-syspro/contracts/address": path.resolve(__dirname, "../../packages/contracts/src/address.ts"),
      "@dosc-syspro/contracts/documento": path.resolve(__dirname, "../../packages/contracts/src/documento.ts"),
      "@dosc-syspro/contracts/documento-config": path.resolve(__dirname, "../../packages/contracts/src/documento-config.ts"),
      "@dosc-syspro/contracts/user": path.resolve(__dirname, "../../packages/contracts/src/user.ts"),
      "@dosc-syspro/contracts/ticket-api": path.resolve(__dirname, "../../packages/contracts/src/ticket-api.ts"),
      "@dosc-syspro/database": path.resolve(__dirname, "../../packages/database/src/index.ts"),
      "@dosc-syspro/remote-infra": path.resolve(__dirname, "../../packages/remote-infra/src/index.ts"),
      "@dosc-syspro/remote-infra/remote-session-port": path.resolve(__dirname, "../../packages/remote-infra/src/remote-session-port.ts"),
      "@dosc-syspro/remote-infra/remote-host-admin-port": path.resolve(__dirname, "../../packages/remote-infra/src/remote-host-admin-port.ts"),
      "@dosc-syspro/remote-infra/remote-address-book-port": path.resolve(__dirname, "../../packages/remote-infra/src/remote-address-book-port.ts"),
    },
  },
});
