// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uistate} from '../models';

export function GetSetupStatus():Promise<uistate.SetupStatus>;

export function GetSummary():Promise<uistate.Summary>;

export function GetSupportSession():Promise<uistate.SupportSession>;

export function ListNotifications():Promise<Array<uistate.Notification>>;

export function OpenSetupExperience():Promise<uistate.ActionResult>;

export function OpenRemoteClient():Promise<uistate.ActionResult>;

export function OpenSupportConversation():Promise<uistate.ActionResult>;

export function SyncSupportConversationContext(arg1:string):Promise<uistate.SupportContextSyncResult>;
