// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentTarget() {
  return window['go']['uiwails']['API']['GetCurrentTarget']();
}

export function GetSetupStatus() {
  return window['go']['uiwails']['API']['GetSetupStatus']();
}

export function GetSummary() {
  return window['go']['uiwails']['API']['GetSummary']();
}

export function GetSupportSession() {
  return window['go']['uiwails']['API']['GetSupportSession']();
}

export function ListNotifications() {
  return window['go']['uiwails']['API']['ListNotifications']();
}

export function OpenRemoteClient() {
  return window['go']['uiwails']['API']['OpenRemoteClient']();
}

export function OpenSetupExperience() {
  return window['go']['uiwails']['API']['OpenSetupExperience']();
}

export function OpenSupportConversation() {
  return window['go']['uiwails']['API']['OpenSupportConversation']();
}

export function SyncSupportConversationContext(arg1) {
  return window['go']['uiwails']['API']['SyncSupportConversationContext'](arg1);
}
