// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

const win = /** @type {any} */ (window);

export function GetCurrentTarget() {
  return win['go']['uiwails']['API']['GetCurrentTarget']();
}

export function GetSetupStatus() {
  return win['go']['uiwails']['API']['GetSetupStatus']();
}

export function GetSummary() {
  return win['go']['uiwails']['API']['GetSummary']();
}

export function GetSupportSession() {
  return win['go']['uiwails']['API']['GetSupportSession']();
}

export function ListNotifications() {
  return win['go']['uiwails']['API']['ListNotifications']();
}

export function OpenRemoteClient() {
  return win['go']['uiwails']['API']['OpenRemoteClient']();
}

export function OpenSetupExperience() {
  return win['go']['uiwails']['API']['OpenSetupExperience']();
}

export function OpenSupportConversation() {
  return win['go']['uiwails']['API']['OpenSupportConversation']();
}

/**
 * @param {string} arg1
 */
export function SyncSupportConversationContext(arg1) {
  return win['go']['uiwails']['API']['SyncSupportConversationContext'](arg1);
}

