export type {
  TicketArticleItem,
  TicketDetailsItem,
  TicketListItem,
  TicketMessagePagination,
  TicketPriorityLevel,
  TicketsPagination,
  TicketStatusCounts,
  TicketTeamFilter,
  ClosedTicketsWindow,
  TicketSortBy,
  TicketSortOrder,
  TicketQueryParams,
  TicketsDataResponse,
} from "@/features/tickets/domain/ticket-model";
