export {
  createCompanySchema,
  COMPANY_REMOTE_CONNECTION_TYPE_VALUES,
  COMPANY_SERVER_PROTOCOL_VALUES,
  COMPANY_SERVER_TYPE_VALUES,
  DEFAULT_COMPANY_INSTALLATION_DIRECTORY,
  DEFAULT_COMPANY_SERVER_HOST,
  DEFAULT_COMPANY_SERVER_PORT,
  DEFAULT_COMPANY_SERVER_PROTOCOL,
  DEFAULT_COMPANY_SERVER_TYPE,
} from "@dosc-syspro/contracts/company";
export type { CreateCompanyInput, CreateCompanyOutput } from "@dosc-syspro/contracts/company";
