export const GRUPOS_DOCUMENTO = [
    { value: "EAJ", label: "AJUSTE DE ESTOQUE" },
    { value: "FDE", label: "DESPESAS C/ AGUA E ESGOTO / GAS" },
    { value: "EBC", label: "EMISSAO BONIFICACAO CONCEDIDA" },
    { value: "EDV", label: "EMISSAO DE DEVOLUCAO DE VENDA" },
    { value: "EDO", label: "EMISSAO DE DOACOES" },
    { value: "ENP", label: "EMISSAO DE NOTA FISCAL DE VENDA PDV" },
    { value: "ETM", label: "EMISSAO DE TRANSFERENCIA PARA PRODUCAO" },
    { value: "EVP", label: "EMISSAO DE VENDA DE PRODUTOS PDV" },
    { value: "EVD", label: "EMISSAO DE VENDA DIRETA DE MERCADORIAS" },
    { value: "EOS", label: "EMISSAO DE VENDA FUTURA" },
    { value: "EDC", label: "EMISSAO DEVOLUCAO DE COMPRA" },
    { value: "EPE", label: "EMISSAO PERDAS E FURTOS DE MERCADORIA" },
    { value: "ESS", label: "EMISSAO POR SIMPLES REMESSA" },
    { value: "EST", label: "EMISSAO POR TRANSFERENCIA DE MERCADORIA" },
    { value: "PCP", label: "PEDIDO DE COMPRA" },
    { value: "EBR", label: "RECEBIMENTO DE BONIFICACAO" },
    { value: "EAQ", label: "RECEBIMENTO DE MERCADORIAS" },
    { value: "ECI", label: "RECEBIMENTO DE MERCADORIAS PARA CONSUMO INTERNO" },
    { value: "EOE", label: "RECEBIMENTO POR OUTRAS ENTRADAS" },
    { value: "EPD", label: "RECEBIMENTO POR PRODUCAO DE MERCADORIA" },
    { value: "EES", label: "RECEBIMENTO POR SIMPLES REMESSA" },
    { value: "EET", label: "RECEBIMENTO POR TRANSFERENCIA DE MERCADORIA" },
    { value: "ETE", label: "RECEBIMENTO POR TROCA DE MERCADORIA" },
] as const;